### ISSUE TITLE
H1N1pdm failing due to mismatched epitope mask length

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#108]
@huddlej ---

Could you take another pass at sequence length issues? I made a couple hacks to just get a build running:

* https://github.com/nextstrain/augur/pull/106
* https://github.com/nextstrain/augur/commit/8d6b680cf246d9ae536fe3379e881da04336db72
* https://github.com/nextstrain/augur/commit/e1a3f38dc69622716feb8df598bcdd68c32c345a#diff-0eb4cb081fa9e2d524e4c86c3b329ab4R133

This worked for H3, Vic and Yam, but now H1 is throwing the following error:

```
Calculating scores with epitope mask 'canton' and glycosylation mask 'ha1_globular_head_h1n1pdm'.
Traceback (most recent call last):
  File "flu.process.py", line 617, in <module>
    glyc_mask_version=runner.config["glyc_mask_version"]
  File "/fh/fast/bedford_t/nextflu/augur-live/builds/flu/scores.py", line 150, in calculate_sequence_scores
    node.attr['ep'] = mask_distance(total_aa_seq, root_total_aa_seq, epitope_mask)
  File "/fh/fast/bedford_t/nextflu/augur-live/builds/flu/scores.py", line 104, in mask_distance
    sites_A = mask_sites(aaA, mask)
  File "/fh/fast/bedford_t/nextflu/augur-live/builds/flu/scores.py", line 100, in mask_sites
    return aa[mask[:len(aa)]]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 567 but corresponding boolean dimension is 566
```

**Comment by huddlej** [comment]
Resolved by #110.

**Comment by ammaraziz** [comment]
Posting this here for others who come across this issue. The above error will be produced if your reference contains gaps.

**Comment by victorlin** [comment]
@ammaraziz we can treat that as an unresolved bug if something is still throwing an uncaught `IndexError`. What `augur` command are you running? If you could open as a new [bug report](https://github.com/nextstrain/augur/issues/new?labels=bug&template=bug_report.md) that would be great.

**Comment by ammaraziz** [comment]
While in the process of submitting a bug report and producing a reproducible example, I discovered that this happens when the reference sequence used in `augur ancestral` is shorter than the original alignments. In other words in my pipeline I used the wrong reference for `augur ancestral`. Not sure how this happened tbh, bad coding while sick.

To replicate this issue, run all usual up to `augur ancestral` but for this step, modify the reference to be shorter (or longer) than the input alignment. 

@victorlin Do you still want me to submit a bug report if it's caused by a dumb user mistake?

**Comment by victorlin** [comment]
@ammaraziz no worries! Yes that bug report would be great. In general, any uncaught error that shows this message can be considered a bug:

```
An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>
```

In this case, Augur should catch the `IndexError` and print a more user-friendly error message describing how to resolve the issue.
